[SERVICE]
    Flush        1
    Log_Level    info

    Parsers_File /fluent-bit/etc/parsers.conf

    storage.path /fluent-bit/state
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit 50M


# ============================================================
# Laravel JSON logs
# ============================================================

[INPUT]
    Name              tail
    Tag               laravel.api
    Path              /var/www/html/storage/logs/json/*.log

    Parser            laravel_json

    DB                /fluent-bit/state/laravel.db

    Read_from_Head    On
    Refresh_Interval   5

    Skip_Long_Lines   On


# ============================================================
# Docker container logs
# ============================================================

[INPUT]
    Name              tail
    Tag               docker.*
    Path              /var/lib/docker/containers/*/*.log

    Parser            docker

    DB                /fluent-bit/state/docker.db

    Read_from_Head    On
    Refresh_Interval   5

    Skip_Long_Lines   On


# ============================================================
# Laravel -> Data Prepper
# ============================================================

[OUTPUT]
    Name              http
    Match             laravel.*

    Host              data-prepper
    Port              2021
    URI               /laravel/logs

    Format            json
    Json_Date_Key     @timestamp
    Json_Date_Format  iso8601


# ============================================================
# Docker -> Data Prepper
# ============================================================

[OUTPUT]
    Name              http
    Match             docker.*

    Host              data-prepper
    Port              2022
    URI               /container/logs

    Format            json
    Json_Date_Key     @timestamp
